/**
 * authmesh CLI — unified credential mesh for OpenCode providers.
 */

import { PROVIDERS, getProvider } from './providers.js'
import { Vault, mask } from './vault.js'
import { buildEnv, injectedKeys, spawnWithEnv } from './inject.js'
import { readFileSync } from 'node:fs'

function usage(): string {
  return `authmesh — unified credential mesh for OpenCode providers

Usage:
  authmesh add <provider> [value]        Store/update a credential (value from arg or stdin)
  authmesh list                          List stored providers (masked)
  authmesh show <provider> [--reveal]    Show a credential (masked by default)
  authmesh remove <provider>             Remove a credential
  authmesh env                           Print export lines for shell sourcing
  authmesh run -- <cmd...>               Run a command with credentials injected
  authmesh providers                     List known providers and their key names
  authmesh health                        Check vault status

Providers: ${PROVIDERS.map(p => p.id).join(', ')}

Data directory: ~/.authmesh (override with AUTHMESH_DATA_DIR)
`
}

function getArg(args: string[], name: string): string | undefined {
  const i = args.indexOf(name)
  return i >= 0 ? args[i + 1] : undefined
}

function hasFlag(args: string[], name: string): boolean {
  return args.includes(name)
}

function readStdinValue(): string {
  try {
    return readFileSync(0, 'utf-8').trim()
  } catch {
    return ''
  }
}

async function main(): Promise<void> {
  const args = process.argv.slice(2)
  const cmd = args[0] ?? ''

  if (cmd === '' || cmd === 'help' || cmd === '--help' || cmd === '-h') {
    console.log(usage())
    return
  }

  const vault = new Vault()

  switch (cmd) {
    case 'add': {
      const providerId = args[1]
      if (!providerId) {
        console.error('Usage: authmesh add <provider> [value]')
        process.exitCode = 1
        return
      }
      const provider = getProvider(providerId)
      if (!provider) {
        console.error(`Unknown provider: ${providerId}. Known: ${PROVIDERS.map(p => p.id).join(', ')}`)
        process.exitCode = 1
        return
      }
      let value = args[2]
      if (!value) {
        value = readStdinValue()
      }
      if (!value) {
        console.error(`No value provided for ${providerId}. Pass it as an argument or pipe it via stdin.`)
        process.exitCode = 1
        return
      }
      const credential = vault.add(provider.id, provider.keyName, value)
      console.log(`Stored ${provider.id} → ${provider.keyName} (${mask(credential.value)})`)
      return
    }

    case 'list': {
      const credentials = vault.getAll()
      if (credentials.length === 0) {
        console.log('No credentials stored. Add one: authmesh add openai sk-...')
        return
      }
      console.log(`AuthMesh — ${credentials.length} credential(s)\n`)
      for (const c of credentials) {
        const provider = getProvider(c.provider)
        console.log(`  ${c.provider}${provider ? ` (${provider.name})` : ''} → ${c.keyName}: ${mask(c.value)}`)
      }
      return
    }

    case 'show': {
      const providerId = args[1]
      if (!providerId) {
        console.error('Usage: authmesh show <provider> [--reveal]')
        process.exitCode = 1
        return
      }
      const credential = vault.get(providerId)
      if (!credential) {
        console.error(`No credential for ${providerId}`)
        process.exitCode = 1
        return
      }
      const reveal = hasFlag(args, '--reveal')
      console.log(`${credential.provider} → ${credential.keyName}: ${reveal ? credential.value : mask(credential.value)}`)
      if (!reveal) {
        console.log('Use --reveal to print the full value.')
      }
      return
    }

    case 'remove': {
      const providerId = args[1]
      if (!providerId) {
        console.error('Usage: authmesh remove <provider>')
        process.exitCode = 1
        return
      }
      const removed = vault.remove(providerId)
      if (removed) {
        console.log(`Removed: ${providerId}`)
      } else {
        console.error(`No credential for ${providerId}`)
        process.exitCode = 1
      }
      return
    }

    case 'env': {
      const credentials = vault.getAll()
      if (credentials.length === 0) {
        console.log('# No credentials stored.')
        return
      }
      console.log('# Generated by authmesh — source with: eval "$(authmesh env)"')
      for (const c of credentials) {
        console.log(`export ${c.keyName}='${c.value.replace(/'/g, `'\\''`)}'`)
      }
      return
    }

    case 'run': {
      const dashIdx = args.indexOf('--')
      if (dashIdx < 0 || dashIdx === args.length - 1) {
        console.error('Usage: authmesh run -- <cmd...>')
        process.exitCode = 1
        return
      }
      const credentials = vault.getAll()
      if (credentials.length === 0) {
        console.error('No credentials stored. Add one first: authmesh add openai sk-...')
        process.exitCode = 1
        return
      }
      const command = args[dashIdx + 1]!
      const cmdArgs = args.slice(dashIdx + 2)
      const keys = injectedKeys(credentials)
      if (keys.length > 0) {
        console.error(`Injected: ${keys.join(', ')}`)
      }
      const child = spawnWithEnv(command, cmdArgs, credentials)
      child.on('exit', code => {
        process.exitCode = code ?? 1
      })
      return
    }

    case 'providers': {
      console.log('Known providers:')
      for (const p of PROVIDERS) {
        console.log(`  ${p.id.padEnd(10)} ${p.name.padEnd(18)} ${p.keyName} (${p.hint})`)
      }
      return
    }

    case 'health': {
      const meta = vault.getMeta()
      console.log(JSON.stringify({
        status: 'ok',
        dataDir: process.env['AUTHMESH_DATA_DIR'] ?? `${process.env['HOME'] ?? ''}/.authmesh`,
        credentials: meta.count,
        providers: PROVIDERS.length,
      }, null, 2))
      return
    }

    default: {
      console.error(`Unknown command: ${cmd}\n`)
      console.error(usage())
      process.exitCode = 1
    }
  }
}

main().catch(err => {
  console.error(err)
  process.exitCode = 1
})